version: "3"

services:
  sample-service:
    build: .

    expose:
      - "8080"

    ports:
      - "8080:8080"

    depends_on:
      - productdb

    environment:
      CONNECTION_STRING: postgresql://product_robot:pr0dr0b0t@productdb:5432/product

  productdb:
    image: postgres:11

    volumes:
      # Volume for startup scripts. Note this willonly run if there is nothing in /var/lib/postgresql/data
      - ./devdatabase/db-init-scripts:/docker-entrypoint-initdb.d

      # Volume for persistance between runs. Uncomment if you wish to retain data.
      # - ./devdatabase/volume:/var/lib/postgresql/data

    expose:
      - "5432"

    ports:
      - "5432:5432"

    environment:
      POSTGRES_PASSWORD: pgsqlDev01
